### ISSUE TITLE
Catalog search return 500 Server error if cloudCover filter's value is float formatted

### ISSUE THREAD

**Issue by ClementPeyrardGSI** [DigitalGlobe/gbdxtools#205]
Hi,

When using a list of filters in the `gbdx.catalog.search()` method, it seems that if the parameter for `cloudCover` is converted to a `string` from a `float`, the server returns the following error: 

`Error: 500 Server Error: Internal Server Error for url: https://geobigdata.io/catalog/v2/search`

Here is an example of request that reproduces the error:
```
wkt_string = "POLYGON((-113.88427734375 40.36642741921034,-110.28076171875 40.36642741921034,-110.28076171875 37.565262680889965,-113.88427734375 37.565262680889965,-113.88427734375 40.36642741921034))"

filters = [
        "(sensorPlatformName = 'WORLDVIEW01' OR sensorPlatformName ='QUICKBIRD02')",
        "cloudCover < 10.0", # instead of 10
        "offNadirAngle > 10"
]

results = gbdx.catalog.search(searchAreaWkt=wkt_string,
                          startDate="2004-01-01T00:00:00.000Z",
                          endDate="2012-01-01T00:00:00.000Z",
                          filters=filters)

```

**Comment by chelm** [comment]
@ClementPeyrardGSI Great catch, thanks! Unfortunately i dont think there's anything gbdxtools can do to protect itself from this on the client side, but i can reach out to the catalog folks and see if we can handle this better. At the very least a decent error would be nice.

**Comment by chelm** [comment]
@ClementPeyrardGSI So i've heard back on this and it sounds like there are a number issues/blockers with returning decent errors or even casting the cloud cover filters to ints. In the backend data store, something we call `VectorServices`, the actual field name for cloudCover is actually `cloudCover_int`. So its probably a matter getting better documentation or migrating to using vector services directly, which gbdxtools supports via the `gbdx.vectors` module. 

The backend team is going to work on trying to surface more meaningful errors, but since this is directly related a gbdxtools bug im going to close it.
