### ISSUE TITLE
support dask 0.16.0

### ISSUE THREAD

**Issue by chelm** [DigitalGlobe/gbdxtools#209]
Currently we're pinning our dask version to the 0.15.4 version as 0.16.0 is giving us problems with our metaclass implementation.

**Comment by chelm** [comment]
@pramukta hoping you might be able to shed some light on the fix for this.

**Comment by pramukta** [comment]
@chelm Let me look into it again.  I remember it had to do with our use of metaclasses (which we may not need) in order to extend `da.Array`.  Some change to dask messed with that, likely to enable their custom container mechanism.  We could migrate to that but not clear how convenient it is because we really want to extend `da.Array` rather than a raw dask container.

**Comment by pramukta** [comment]
@chelm, yup so in order to implement custom containers, the dask repo moved to using our strategy of using `ABCMeta` to enable implementing extensions, which is now colliding (because issubclass is being called recursively and unconditionally in the process)

**Comment by pramukta** [comment]
@chelm there may be a hacky fix by adjusting the condition here https://github.com/DigitalGlobe/gbdxtools/blob/master/gbdxtools/images/meta.py#L101 but the correct approach is probably to replace the `__daskmeta__` interface with the new recommended one and make GeoImage non-abstract.  This may be best done as a large changeset (or at least worked on in concert with) #201 since that will require hooking into the dask optimizer to circumvent the 1 thread per connection pattern we currently have for accessing RDA (to get to the 1000s of connections we need to get the desired speeds for fitting models).

**Comment by pramukta** [comment]
I pushed a quick hack fix to https://github.com/DigitalGlobe/gbdxtools/tree/209-dask-16-hack

Unsure how comprehensive it is, so not good to merge recklessly

**Comment by chelm** [comment]
@pramukta thanks! I'll take a look today and set up an env to test things out and comb over. Will ping you with questions.

**Comment by chelm** [comment]
@pramukta I dont see any commits on that branch, can you point me to the changes you made?

**Comment by pramukta** [comment]
It's one commit on the line referenced above

**Comment by chelm** [comment]
Ahh i see it, thanks

**Comment by chelm** [comment]
PR merged
