### ISSUE TITLE
Write function which allows user to register new task.

### ISSUE THREAD

**Issue by nricklin** [DigitalGlobe/gbdxtools#9]
_From @kostasthebarbarian on April 2, 2016 0:41_

It should be trivial to register a new task.

_Copied from original issue: kostasthebarbarian/gbdxtools#20_

**Comment by kstamatiou** [comment]
What do we mean here? Should task creation be possible via gbdxtools? Not trivial.

**Comment by willcadell** [comment]
Could a user/script supply/create a json file to register the task against? 
That said, task registration is only done once per task rather than multiple times, so maybe this is more of a command line activity that a repeatable / scripting activity. Perhaps a check to see if a task is registered is more appropriate?

**Comment by kstamatiou** [comment]
@willcadell, @mjost5v you guys are working on this, right? Want to come up with a set of well defined issues?

**Comment by kstamatiou** [comment]
Solved with the task_registry module. Closing.
